
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='igit',
    version='0.1.0',
    description='Top-level package for igit.',
    python_requires='>=3.7',
    project_urls={"homepage": "https://github.com/jmosbacher/igit"},
    author='Yossi Mosbacher',
    author_email='joe.mosbacher@gmail.com',
    license='Apache-2.0',
    classifiers=['Development Status :: 2 - Pre-Alpha', 'Intended Audience :: Developers', 'License :: OSI Approved :: Apache Software License', 'Natural Language :: English', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8'],
    entry_points={"console_scripts": ["igit = igit.cli:main"]},
    packages=['igit'],
    package_dir={"": "."},
    package_data={},
    install_requires=['click', 'intervaltree==3.*,>=3.1.0'],
    extras_require={"dev": ["bumpversion", "coverage", "dephell", "flake8", "invoke", "isort", "nbsphinx", "pylint", "pytest", "sphinx", "sphinx-material", "tox", "yapf"]},
)
